name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g yarn
        yarn install

    - name: Build the application 
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env # Set environment variable
        cat .env # Debug: Print environment variables
        yarn build    

    - name: ZIP application package
      run: zip -r app.zip . -x "node_modules/*" ".git/*" "*.zip"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload app.zip to S3
      run: |
        aws s3 cp app.zip s3://${{ secrets.EB_S3_BUCKET }}
      env:
        S3_BUCKET: ${{ secrets.EB_S3_BUCKET }}
